<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520140343 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE gtfs_calendar (service_id VARCHAR(64) NOT NULL, monday BOOLEAN NOT NULL, tuesday BOOLEAN NOT NULL, wednesday BOOLEAN NOT NULL, thursday BOOLEAN NOT NULL, friday BOOLEAN NOT NULL, saturday BOOLEAN NOT NULL, sunday BOOLEAN NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, PRIMARY KEY (service_id))');
        $this->addSql('CREATE TABLE gtfs_calendar_date (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, service_id VARCHAR(64) NOT NULL, date DATE NOT NULL, exception_type INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_calendar_date ON gtfs_calendar_date (date)');
        $this->addSql('CREATE TABLE gtfs_route (id VARCHAR(64) NOT NULL, short_name VARCHAR(32) DEFAULT NULL, long_name VARCHAR(255) DEFAULT NULL, type INT NOT NULL, color VARCHAR(7) DEFAULT NULL, text_color VARCHAR(7) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE gtfs_stop (id VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, latitude NUMERIC(9, 6) NOT NULL, longitude NUMERIC(9, 6) NOT NULL, location_type INT DEFAULT NULL, parent_station VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_stop_name ON gtfs_stop (name)');
        $this->addSql('CREATE INDEX idx_stop_coords ON gtfs_stop (latitude, longitude)');
        $this->addSql('CREATE TABLE gtfs_stop_time (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stop_sequence INT NOT NULL, arrival_seconds INT NOT NULL, departure_seconds INT NOT NULL, stop_headsign VARCHAR(255) DEFAULT NULL, trip_id VARCHAR(64) NOT NULL, stop_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C92D2417A5BC2E0E ON gtfs_stop_time (trip_id)');
        $this->addSql('CREATE INDEX IDX_C92D24173902063D ON gtfs_stop_time (stop_id)');
        $this->addSql('CREATE INDEX idx_stoptime_stop_dep ON gtfs_stop_time (stop_id, departure_seconds)');
        $this->addSql('CREATE INDEX idx_stoptime_trip ON gtfs_stop_time (trip_id, stop_sequence)');
        $this->addSql('CREATE TABLE gtfs_trip (id VARCHAR(64) NOT NULL, service_id VARCHAR(64) NOT NULL, headsign VARCHAR(255) DEFAULT NULL, direction_id INT DEFAULT NULL, route_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_trip_service ON gtfs_trip (service_id)');
        $this->addSql('CREATE INDEX idx_trip_route ON gtfs_trip (route_id)');
        $this->addSql('CREATE TABLE velivert_station (id VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, latitude NUMERIC(9, 6) NOT NULL, longitude NUMERIC(9, 6) NOT NULL, capacity INT NOT NULL, bikes_available INT NOT NULL, docks_available INT NOT NULL, is_installed BOOLEAN NOT NULL, is_renting BOOLEAN NOT NULL, is_returning BOOLEAN NOT NULL, last_reported_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE gtfs_stop_time ADD CONSTRAINT FK_C92D2417A5BC2E0E FOREIGN KEY (trip_id) REFERENCES gtfs_trip (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gtfs_stop_time ADD CONSTRAINT FK_C92D24173902063D FOREIGN KEY (stop_id) REFERENCES gtfs_stop (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gtfs_trip ADD CONSTRAINT FK_7E90132434ECB4E6 FOREIGN KEY (route_id) REFERENCES gtfs_route (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA tiger_data');
        $this->addSql('CREATE SCHEMA tiger');
        $this->addSql('CREATE SCHEMA topology');
        $this->addSql('ALTER TABLE gtfs_stop_time DROP CONSTRAINT FK_C92D2417A5BC2E0E');
        $this->addSql('ALTER TABLE gtfs_stop_time DROP CONSTRAINT FK_C92D24173902063D');
        $this->addSql('ALTER TABLE gtfs_trip DROP CONSTRAINT FK_7E90132434ECB4E6');
        $this->addSql('DROP TABLE gtfs_calendar');
        $this->addSql('DROP TABLE gtfs_calendar_date');
        $this->addSql('DROP TABLE gtfs_route');
        $this->addSql('DROP TABLE gtfs_stop');
        $this->addSql('DROP TABLE gtfs_stop_time');
        $this->addSql('DROP TABLE gtfs_trip');
        $this->addSql('DROP TABLE velivert_station');
    }
}
