<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * GTFS-Realtime support: trip-stop patches + feed status singleton.
 */
final class Version20260522141500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add gtfs_rt_trip_update and gtfs_rt_feed_status tables for GTFS-RT integration.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE gtfs_rt_trip_update (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trip_id VARCHAR(64) DEFAULT NULL,
                route_id VARCHAR(64) DEFAULT NULL,
                start_date VARCHAR(8) DEFAULT NULL,
                stop_id VARCHAR(64) DEFAULT NULL,
                stop_sequence INT DEFAULT NULL,
                delay_seconds INT NOT NULL,
                schedule_relationship SMALLINT NOT NULL,
                trip_canceled BOOLEAN NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_rt_trip_stop ON gtfs_rt_trip_update (trip_id, start_date, stop_id)');
        $this->addSql('CREATE INDEX idx_rt_trip_seq  ON gtfs_rt_trip_update (trip_id, start_date, stop_sequence)');

        $this->addSql(<<<'SQL'
            CREATE TABLE gtfs_rt_feed_status (
                id VARCHAR(16) NOT NULL,
                last_success_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                last_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                last_row_count INT NOT NULL DEFAULT 0,
                consecutive_failures INT NOT NULL DEFAULT 0,
                last_error VARCHAR(255) DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql("INSERT INTO gtfs_rt_feed_status (id, last_row_count, consecutive_failures) VALUES ('stas', 0, 0)");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS gtfs_rt_trip_update');
        $this->addSql('DROP TABLE IF EXISTS gtfs_rt_feed_status');
    }
}
